//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace GrowCreate.Core.Models
{
	/// <summary>Currency</summary>
	[PublishedContentModel("currency")]
	public partial class Currency : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "currency";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Currency(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Currency, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Currency Code: 3 character currency code, e.g. GBP, EUR etc. This is used to look up conversion rates.
		///</summary>
		[ImplementPropertyType("currencyCode")]
		public string CurrencyCode
		{
			get { return this.GetPropertyValue<string>("currencyCode"); }
		}

		///<summary>
		/// Currency Name: Name of currency
		///</summary>
		[ImplementPropertyType("currencyName")]
		public string CurrencyName
		{
			get { return this.GetPropertyValue<string>("currencyName"); }
		}

		///<summary>
		/// Currency Symbol: Eg. £, $
		///</summary>
		[ImplementPropertyType("currencySymbol")]
		public string CurrencySymbol
		{
			get { return this.GetPropertyValue<string>("currencySymbol"); }
		}
	}
}
